name: Custom version modpack build

on:
  workflow_dispatch:
    inputs:
      daxxl-tag:
        description: DAXXL Tag to build
        default: experimental
        type: string
        required: true

jobs:
  modpack-build:
    name: Build ${{ inputs.daxxl-tag }}
    runs-on: ubuntu-24.04
    env:
      DAXXL_TAG: ${{ inputs.daxxl-tag }}
    steps:
      #  check-out repo and set-up python
      - name: Check out repository
        uses: actions/checkout@v5
        with:
          token: ${{ secrets.NIGHTLY_GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Verify manifest
        shell: bash
        run: |
          jq -e >/dev/null < "releases/manifests/${DAXXL_TAG}.json"

      - name: Install uv
        uses: astral-sh/setup-uv@v8.1.0
        with:
          python-version: 3.11
          enable-cache: true

      - name: Install dependencies
        run: uv sync --locked --all-extras --dev

      - name: Get current date
        id: date
        shell: bash
        run: |
          echo "today=$(date --iso-8601)+${{ github.run_number }}" >> "$GITHUB_OUTPUT"
          echo "cachedate=$(date '+%G-w%V')" >> "$GITHUB_OUTPUT"

      - name: Load cached mod zips
        id: load_mod_cache
        uses: actions/cache/restore@v4
        with:
          path: cache
          key: daxxl-${{ runner.os }}-${{ inputs.daxxl-tag }}-${{ steps.date.outputs.cachedate }}
          restore-keys: |
            daxxl-${{ runner.os }}-${{ inputs.daxxl-tag }}-
            daxxl-${{ runner.os }}-

      - name: Build modpack archives
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.NIGHTLY_GITHUB_TOKEN }}
        run: |
          uv run python -m daxxl.cli.download_release "${DAXXL_TAG}"
          uv run python -m daxxl.cli.assemble_release CLIENT "${DAXXL_TAG}"
          uv run python -m daxxl.cli.assemble_release SERVER "${DAXXL_TAG}"
          uv run python -m daxxl.cli.assemble_release CLIENT_JAVA9 "${DAXXL_TAG}"
          uv run python -m daxxl.cli.assemble_release SERVER_JAVA9 "${DAXXL_TAG}"

      - name: Save cached mod zips
        uses: actions/cache/save@v4
        if: steps.load_mod_cache.outputs.cache-hit != 'true'
        with:
          path: cache
          key: daxxl-${{ runner.os }}-${{ inputs.daxxl-tag }}-${{ steps.date.outputs.cachedate }}

      # Upload modpack
      - name: Upload manifest
        uses: actions/upload-artifact@v4
        # Upload all archives even if one of the zips fails to upload
        if: success() || failure()
        with:
          name: gtnh-${{ inputs.daxxl-tag }}-manifest.json
          path: releases/manifests/${{ inputs.daxxl-tag }}.json

      - name: Upload manifest job summary
        shell: bash
        if: success() || failure()
        continue-on-error: true
        run: |
          echo "# GTNH build ${DAXXL_TAG}" >> "$GITHUB_STEP_SUMMARY"
          echo "" >> "$GITHUB_STEP_SUMMARY"

          echo "## Github mods" >> "$GITHUB_STEP_SUMMARY"
          echo "" >> "$GITHUB_STEP_SUMMARY"
          echo "| Mod | Version | Side |" >> "$GITHUB_STEP_SUMMARY"
          echo "| --- | ------- | ---- |" >> "$GITHUB_STEP_SUMMARY"
          jq -r '.github_mods | keys[] as $k | ["", $k, .[$k].version, .[$k].side, ""] | join(" | ") | ltrimstr(" ")' "releases/manifests/${DAXXL_TAG}.json" | sort -f >> "$GITHUB_STEP_SUMMARY"
          echo "" >> "$GITHUB_STEP_SUMMARY"

          echo "## External mods" >> "$GITHUB_STEP_SUMMARY"
          echo "" >> "$GITHUB_STEP_SUMMARY"
          echo "| Mod | Version | Side |" >> "$GITHUB_STEP_SUMMARY"
          echo "| --- | ------- | ---- |" >> "$GITHUB_STEP_SUMMARY"
          jq -r '.external_mods | keys[] as $k | ["", $k, .[$k].version, .[$k].side, ""] | join(" | ") | ltrimstr(" ")' "releases/manifests/${DAXXL_TAG}.json" | sort -f >> "$GITHUB_STEP_SUMMARY"

      - name: Relocate built zips
        shell: bash
        run: |
          mv "releases/zip/GT_New_Horizons_${DAXXL_TAG}_Server_Java_8.zip" "GTNH-${DAXXL_TAG}-server-java8.zip"
          mv "releases/zip/GT_New_Horizons_${DAXXL_TAG}_Server_Java_17-25.zip" "GTNH-${DAXXL_TAG}-server-java17-25.zip"
          mv "releases/multi_poly/GT_New_Horizons_${DAXXL_TAG}_Java_8.zip" "GTNH-${DAXXL_TAG}-mmcprism-java8.zip"
          mv "releases/multi_poly/GT_New_Horizons_${DAXXL_TAG}_Java_17-25.zip" "GTNH-${DAXXL_TAG}-mmcprism-java17-25.zip"

      - name: Upload server zip
        uses: actions/upload-artifact@v7
        # Upload even if one of the zips fails to upload
        if: success() || failure()
        with:
          path: GTNH-${{ inputs.daxxl-tag }}-server-java8.zip
          archive: false

      - name: Upload modern java server zip
        uses: actions/upload-artifact@v7
        # Upload even if one of the zips fails to upload
        if: success() || failure()
        with:
          path: GTNH-${{ inputs.daxxl-tag }}-server-java17-25.zip
          archive: false

      - name: Upload MMC zip
        uses: actions/upload-artifact@v7
        # Upload even if one of the zips fails to upload
        if: success() || failure()
        with:
          path: GTNH-${{ inputs.daxxl-tag }}-mmcprism-java8.zip
          archive: false

      - name: Upload modern java Prism zip
        uses: actions/upload-artifact@v7
        # Upload even if one of the zips fails to upload
        if: success() || failure()
        with:
          path: GTNH-${{ inputs.daxxl-tag }}-mmcprism-java17-25.zip
          archive: false
